spring:
  application:
    name: ms-persona
  datasource:
    url: jdbc:mysql://localhost:3306/persona?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
logstash:
  host: localhost:9201