input {
    tcp {
        port => "9201"
        codec => json_lines

    }
}

filter {
    
    json {
        source => "message"
        target => "message"
    }
}

output {
   elasticsearch {
       hosts => ["http://elasticsearch:9200"]
       index => "micros-%{+YYYY.MM.dd}"
   }

    stdout {}
}

